ALTER TABLE UserEntity
ADD COLUMN wins int NOT NULL DEFAULT 0;
ALTER TABLE UserEntity
ADD COLUMN loses int NOT NULL DEFAULT 0;
ALTER TABLE UserEntity
ADD COLUMN xp int NOT NULL DEFAULT 0;
ALTER TABLE UserEntity
ADD COLUMN streak int NOT NULL DEFAULT 0;

